services:
  - type: web
    name: apix-api
    runtime: docker
    repo: https://github.com/lyc0riz/Smart-Airfare-Price-Index
    plan: free
    dockerfilePath: ./api.Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: API_KEYS
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true
